// Node builtins are used at build time (Vite bundles this config and runs
// it under Node). @types/node is not installed and tsconfig restricts
// ambient types to vite/client, so suppress the missing-declaration errors.
// @ts-ignore
import { copyFileSync, readdirSync, writeFileSync } from 'node:fs';
// @ts-ignore
import { dirname, resolve } from 'node:path';
// @ts-ignore
import { fileURLToPath } from 'node:url';
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { TanStackRouterVite } from '@tanstack/router-plugin/vite';

/**
 * Emit a precache manifest of the build's hashed assets so the service
 * worker can install them. Vite fingerprints every JS/CSS chunk under
 * ``dist/assets/`` (e.g. ``index-DGrELz69.js``); the unhashed sqlite-wasm
 * worker files copied by ``copySqliteWasmFiles`` live at the dist root.
 * Without precaching them the SPA boots blank offline: the SW's
 * stale-while-revalidate fetch handler returns a 504 for any hashed URL
 * it never cached during the brief window the user was online.
 *
 * The manifest is emitted at ``dist/assets/sw-assets.js`` so the existing
 * ``/assets`` StaticFiles mount (which serves every file in that
 * directory as JS) can deliver it to the SW at install time without
 * touching backend routing.
 */
function emitSwPrecacheManifest(): Plugin {
  const configDir = dirname(fileURLToPath(import.meta.url));
  const outDir = resolve(configDir, 'dist');
  const assetsDir = resolve(outDir, 'assets');
  // Unhashed sqlite-wasm files written to dist root by
  // copySqliteWasmFiles() — registered first so its closeBundle runs
  // before this one and the files exist on disk when we emit the
  // manifest.
  const rootSqliteFiles = [
    '/sqlite3-worker1.js',
    '/sqlite3-worker1.mjs',
    '/sqlite3-opfs-async-proxy.js',
    '/sqlite3.wasm',
  ];
  return {
    name: 'emit-sw-precache-manifest',
    apply: 'build',
    closeBundle() {
      let entries: string[];
      try {
        entries = readdirSync(assetsDir);
      } catch {
        // dist/assets/ missing — nothing to precache beyond SHELL.
        entries = [];
      }
      const hashed = entries
        .filter((name: string) => /\.(?:js|css|wasm)$/.test(name))
        .sort()
        .map((name: string) => `/assets/${name}`);
      const all = [...rootSqliteFiles, ...hashed].sort();
      const body =
        `// Generated by vite.config.ts — do not edit.\n` +
        `self.VESPERIKI_PRECACHE_ASSETS = ${JSON.stringify(all, null, 2)};\n`;
      writeFileSync(resolve(assetsDir, 'sw-assets.js'), body);
    },
  };
}

/**
 * Copy the sqlite-wasm browser files into the build root (dist/). The
 * SQLite OPFS VFS requests its worker, async-proxy, and wasm files by
 * UNHASHED root names (/sqlite3-worker1.js, /sqlite3-opfs-async-proxy.js,
 * /sqlite3.wasm), so they must land at dist/ — not under hashed assets/
 * — for the offline WASM database to boot.
 */
function copySqliteWasmFiles(): Plugin {
  const configDir = dirname(fileURLToPath(import.meta.url));
  const sqliteDist = resolve(
    configDir,
    'node_modules/@sqlite.org/sqlite-wasm/dist',
  );
  const outDir = resolve(configDir, 'dist');
  const files: ReadonlyArray<readonly [string, string]> = [
    ['sqlite3-worker1.mjs', 'sqlite3-worker1.mjs'],
    // The runtime may request the worker as either .mjs or .js; ship
    // both names with identical content.
    ['sqlite3-worker1.mjs', 'sqlite3-worker1.js'],
    ['sqlite3-opfs-async-proxy.js', 'sqlite3-opfs-async-proxy.js'],
    ['sqlite3.wasm', 'sqlite3.wasm'],
  ];
  return {
    name: 'copy-sqlite-wasm-files',
    apply: 'build',
    closeBundle() {
      for (const [source, target] of files) {
        copyFileSync(resolve(sqliteDist, source), resolve(outDir, target));
      }
    },
  };
}

export default defineConfig({
  server: {
    proxy: {
      '/api': 'http://localhost:7420',
      '/healthz': 'http://localhost:7420',
    },
  },
  plugins: [
    TanStackRouterVite({ routeFileIgnorePattern: '\\.lazy\\.tsx$' }),
    react(),
    tailwindcss(),
    // copySqliteWasmFiles must register before emitSwPrecacheManifest so
    // the unhashed sqlite files exist at dist/ root when the manifest
    // plugin lists the directory in its closeBundle hook.
    copySqliteWasmFiles(),
    emitSwPrecacheManifest(),
  ],
});
