/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as TagsTagRouteImport } from './routes/tags.$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/$tag',
  path: '/$tag',
  getParentRoute: () => TagsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/search': typeof SearchRoute
  '/tags': typeof TagsRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/tags/$tag': typeof TagsTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/search': typeof SearchRoute
  '/tags': typeof TagsRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/tags/$tag': typeof TagsTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/search': typeof SearchRoute
  '/tags': typeof TagsRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/tags/$tag': typeof TagsTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/graph' | '/search' | '/tags' | '/p/$slug' | '/tags/$tag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/graph' | '/search' | '/tags' | '/p/$slug' | '/tags/$tag'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/search'
    | '/tags'
    | '/p/$slug'
    | '/tags/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  SearchRoute: typeof SearchRoute
  TagsRoute: typeof TagsRouteWithChildren
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tag': {
      id: '/tags/$tag'
      path: '/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof TagsRoute
    }
  }
}

interface TagsRouteChildren {
  TagsTagRoute: typeof TagsTagRoute
}

const TagsRouteChildren: TagsRouteChildren = {
  TagsTagRoute: TagsTagRoute,
}

const TagsRouteWithChildren = TagsRoute._addFileChildren(TagsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  SearchRoute: SearchRoute,
  TagsRoute: TagsRouteWithChildren,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
